### ISSUE TITLE
Controller deployment binds viewer port to 80, which fails

### ISSUE THREAD

**Issue by ctron** [eclipse-iofog/iofog-operator#20]
~~~
Error: listen EACCES 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/usr/local/lib/node_modules/iofogcontroller/node_modules/express/lib/application.js:618:24)
    at startHttpServer (/usr/local/lib/node_modules/iofogcontroller/src/server.js:116:36)
    at initState.then (/usr/local/lib/node_modules/iofogcontroller/src/server.js:199:7)
    at <anonymous>
~~~

I think there should be a way to configure the viewer port using the `VIEWER_PORT` variable.

**Comment by sergerad** [comment]
See [here](https://github.com/eclipse-iofog/iofog-operator/commit/33f6565691a5f6a7869fcf89d42c3f24052805da)
